name: Release
'on':
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'bcook254.adguardhome'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'bcook254.adguardhome'

      - name: Get tags.
        id: tags
        run: |
          git fetch -a
          echo "PREVIOUS=$(git describe --tags --abbrev=0 ${{ github.ref }}^)" >> $GITHUB_OUTPUT
      
      - name: Create release.
        uses: softprops/action-gh-release@v2
        with:
          body: |
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.tags.outputs.PREVIOUS }}...${{ github.ref_name }}

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
